;; data.lisp --- emitters for FileNode, LayoutWorkspace, scan messages.
;; NOTE: no `pub` anywhere: single binary crate, tests access via `super::*`.
;; Behavior-identical to 01_more, avoids the struct-field visibility hatch.
(in-package :cl-rust-generator)
(defun emit-file-node-struct ()
  `(defstruct0 FileNode
     (name String)
     (is_dir bool)
     (size_bytes u64)
     (children "Vec<FileNode>")
     (is_sorted bool)
     (color Color)
     (target_rect Rect)
     (current_rect Rect)
     (growth_pulse f32)
     (growth_rate f64)
     (last_change_time Instant)
     )
  )
(defun emit-file-node-new ()
  `(defun new (name is_dir size_bytes)
     (declare (type String name) (type bool is_dir) (type u64 size_bytes)
              (values Self)
              )
     (let ((color (if is_dir
                      (Color--new 0.14s0 0.16s0 0.20s0 1.0s0)
                      (get_color_for_filename (ref name))
                      )
                  )
            )
       (make-instance Self name is_dir size_bytes
                      :children (Vec--new)
                      :is_sorted false
                      color
                      :target_rect (Rect--default)
                      :current_rect (Rect--default)
                      :growth_pulse 0.0
                      :growth_rate 0.0
                      :last_change_time (Instant--now)
                      )
       )
     )
  )
;; NOTE: iterative descent (? operator) instead of &components[1..]:
;; aref wraps compound indices in parens (unused_parens). Same behavior.
(defun emit-find-mut ()
  `(defun find_mut ("&mut self" "components: &[&OsStr]")
     (declare (values "Option<&mut FileNode>"))
     (let ((current self)
           )
       (declare (mutable current))
       (for (component components)
            (let ((target (dot component (to_string_lossy)))
                  )
              (let ((next (? (dot (dot current children)
                                  (iter_mut)
                                  (find (lambda (c)
                                          (== (dot c name) target)
                                          )
                                        )
                                  )
                             )
                        )
                    )
                (= current next)
                )
              )
            )
       (Some current)
       )
     )
  )
;; NOTE: position-based recursion (start: usize) instead of
;; &components[1..]: aref wraps compound indices in parens
;; (unused_parens). update_file_size keeps its 01_more signature.
(defun emit-update-at-leaf ()
  `(when (>= start (dot components (len)))
         (let ((old_size (dot self size_bytes))
               (diff (- (coerce new_size i64) (coerce old_size i64)))
               )
           (when (!= diff 0)
             (let ((dt (dot (- now (dot self last_change_time)) (as_secs_f64) (max 0.01)))
                   )
               (when (< 0 diff)
                 (= (dot self growth_pulse) 1.0)
                 (= (dot self growth_rate) (/ (coerce diff f64) dt))
                 )
               (= (dot self size_bytes) new_size)
               (= (dot self last_change_time) now)
               )
             )
           (return (Some diff))
           )
         )
  )
(defun emit-update-at-descend ()
  `(let ((target (dot (aref components start) (to_string_lossy)))
             )
         (for (child (ref-mut (dot self children)))
              (when (== (dot child name) target)
                (if-let ((Some diff) (dot child (update_at
                                                 components
                                                 (+ start 1)
                                                 new_size
                                                 now
                                                 )
                                      )
                         )
                        (progn
                          (when (!= diff 0)
                            (= (dot self size_bytes)
                               (coerce (dot (+ (coerce (dot self size_bytes) i64) diff)
                                            (max 0)
                                            )
                                       u64
                                       )
                               )
                            (= (dot self is_sorted) false)
                            (when (< 0 diff)
                              (= (dot self growth_pulse)
                                 (dot (+ (dot self growth_pulse) 0.3) (min 1.0))
                                 )
                              )
                            )
                          (return (Some diff))
                          )
                        )
                (break)
                )
              )
         None
         )
  )
(defun emit-update-file-size ()
  (list
    `(defun update_file_size ("&mut self" "components: &[&OsStr]" "new_size: u64" "now: Instant")
       (declare (type u64 new_size) (type Instant now)
                (values "Option<i64>")
                )
       (dot self (update_at components 0 new_size now))
       )
    `(defun update_at ("&mut self" "components: &[&OsStr]" "start: usize" "new_size: u64" "now: Instant")
       (declare (type u64 new_size) (type Instant now)
                (values "Option<i64>")
                )
       ,(emit-update-at-leaf)
       ,(emit-update-at-descend)
       )
    )
  )
(defun emit-workspace-and-scan-types ()
  (list
    `(defstruct0 LayoutWorkspace
       (areas "Vec<f64>")
       (row "Vec<usize>")
       )
    `(defstruct0 DirectoryBatch
       (parent_path PathBuf)
       (children "Vec<FileNode>")
       )
    ;; HATCH: defenum covers unit variants only; tuple variant as string.
    "enum ScanEvent { Batch(DirectoryBatch), }"
    )
  )
(defun emit-data ()
  (append
    (list (emit-file-node-struct)
          `(impl FileNode
                 ,(emit-file-node-new)
                 ,(emit-find-mut)
                 ,@(emit-update-file-size)
                 )
          )
    (emit-workspace-and-scan-types)
    )
  )
