;; format.lisp --- emitters for labels, colors, printing, window config.
;; Reformulations (behavior-identical, noted for the walkthrough):
;; - get_color_for_filename: nested ext-is ifs instead of match with |-patterns.
;; - truncate_label: chars().take().collect() instead of byte slicing.
;; - print_line: nested ifs instead of let-chains (if let && ).
;; - window_conf: field assignment on Conf::default() instead of ..-literals.
(in-package :cl-rust-generator)
(defun emit-truncate-label ()
  `(defun truncate_label (&label max_chars)
     (declare (type str &label) (type usize max_chars) (values String))
     (when (or (<= max_chars 3)
               (<= (dot label (chars) (count)) max_chars)
               )
       (return (dot label (to_string)))
       )
     (let ((prefix (dot label (chars) (take (- max_chars 2)) (collect))))
       (declare (type String prefix))
       (format! (string "{}..") prefix)
       )
     )
  )
(defun emit-color-for-filename ()
  `(defun get_color_for_filename (&name)
     (declare (type str &name) (values Color))
     (let ((ext (dot (Path--new name)
                     (extension)
                     (and_then (scope OsStr to_str))
                     (unwrap_or (string ""))
                     (to_lowercase)
                     )
                )
           )
       (if ,(ext-is 'ext '("mp4" "mkv" "avi" "mov"))
           (Color--new 0.72s0 0.23s0 0.86s0 1.0s0)
           (if ,(ext-is 'ext '("mp3" "flac" "wav" "ogg"))
               (Color--new 0.94s0 0.80s0 0.14s0 1.0s0)
               (if ,(ext-is 'ext '("png" "jpg" "jpeg" "webp" "gif"))
                   (Color--new 0.12s0 0.74s0 0.90s0 1.0s0)
                   (if ,(ext-is 'ext '("zip" "rar" "7z" "tar" "gz"))
                       (Color--new 0.92s0 0.20s0 0.20s0 1.0s0)
                       (if ,(ext-is 'ext '("rs" "cpp" "c" "h" "py" "js" "ts" "txt" "md"))
                           (Color--new 0.16s0 0.82s0 0.43s0 1.0s0)
                           (if ,(ext-is 'ext '("exe" "dll" "so" "bin"))
                               (Color--new 0.24s0 0.39s0 0.94s0 1.0s0)
                               (let ((hasher (DefaultHasher--new)))
                                 (declare (mutable hasher))
                                 (dot name (hash (ref-mut hasher)))
                                 (let ((h (dot hasher (finish))))
                                   (Color--from_rgba
                                     (coerce (+ (% (>> h 16) 160) 80) u8)
                                     (coerce (+ (% (>> h 8) 160) 80) u8)
                                     (coerce (+ (% h 160) 80) u8)
                                     255
                                     )
                                   )
                                 )
                               )
                           )
                       )
                   )
               )
           )
       )
     )
  )
;; NOTE: match instead of nested ifs (collapsible_if); same behavior.
(defun emit-print-line ()
  `(defun print_line (line)
     (declare (type String line))
     (let ((stdout (io--stdout))
           (lock (dot stdout (lock)))
           )
       (declare (mutable lock))
       (if-let ((Err e) (writeln! lock (string "{line}")))
               (case (dot e (kind))
                 (io--ErrorKind--BrokenPipe)
                 (t (panic! (string "failed printing to stdout: {e}")))
                 )
               )
       )
     )
  )
(defun emit-format-bytes ()
  `(defun format_bytes (bytes)
     (declare (type u64 bytes) (values String))
     (let ((units (bracket (string "B") (string "KB") (string "MB")
                           (string "GB") (string "TB")
                           )
                  )
           (d (coerce bytes f64))
           (i 0)
           )
       (declare (type usize i) (mutable d i))
       (while (and (<= 1024.0 d) (< i 4))
              ;; HATCH: (/= d 1024.0) emits d/=(1024.0); rustfmt keeps the
              ;; redundant parens (unused_parens). Known from 03.
              "d /= 1024.0;"
              (incf i)
              )
       ;; NOTE: {:.2} is the 01_more reference (03 used {:.1}).
       (format! (string "{:.2} {}") d (aref units i))
       )
     )
  )
;; allow: struct-update syntax (..Default::default()) is not emittable.
(defun emit-window-conf ()
  `(attr "allow(clippy::field_reassign_with_default)"
     (defun window_conf ()
       (declare (values Conf))
     (let ((conf (Conf--default)))
       (declare (mutable conf))
       (= (dot conf window_title) (dot (string "Treemap Disk Visualizer") (to_string)))
       (= (dot conf window_width) 1280)
       (= (dot conf window_height) 720)
       (= (dot conf high_dpi) true)
       (= (dot (dot conf platform) swap_interval) (Some 1))
       conf
       )
       )
     )
  )
(defun emit-format ()
  (list (emit-truncate-label)
        (emit-color-for-filename)
        (emit-print-line)
        (emit-format-bytes)
        (emit-window-conf)
        )
  )
