;; headless.lisp --- emitters for CLI parsing and headless scan mode.
(in-package :cl-rust-generator)
(defun emit-target-from-args ()
  `(defun target_from_args (&args)
     (declare (type "[String]" &args) (values PathBuf))
     (dot args
          (iter)
          (skip 1)
          (find (lambda (a)
                  (and (!= (deref a) (string "--headless"))
                       (!= (deref a) (string "--scan-only"))
                       )
                  )
                )
          (map (scope PathBuf from))
          (unwrap_or_else (lambda ()
                            (PathBuf--from (string "."))
                            )
                          )
          )
     )
  )
(defun emit-resolve-target ()
  `(defun resolve_target (&args)
     (declare (type "[String]" &args) (values "(PathBuf, String)"))
     (let ((raw_target (target_from_args args))
           (target_dir (dot (fs--canonicalize (ref raw_target)) (unwrap_or raw_target)))
           )
       (let ((root_name (dot target_dir
                             (file_name)
                             (map (lambda (s)
                                    (dot s (to_string_lossy) (into_owned))
                                    )
                                  )
                             (unwrap_or_else (lambda ()
                                               (dot target_dir
                                                    (to_string_lossy)
                                                    (into_owned)
                                                    )
                                               )
                                             )
                             )
                        )
             )
         (paren target_dir root_name)
         )
       )
     )
  )
(defun emit-has-display ()
  (list
    `(attr "cfg(target_os = \"linux\")"
       (defun has_graphical_display ()
         (declare (values bool))
         (or (dot (std--env--var_os (string "DISPLAY"))
                          (is_some_and (lambda (v)
                                         (not (dot v (is_empty)))
                                         )
                                       )
                          )
                     (dot (std--env--var_os (string "WAYLAND_DISPLAY"))
                          (is_some_and (lambda (v)
                                         (not (dot v (is_empty)))
                                         )
                                       )
                          )
                     )
         )
       )
    `(attr "cfg(not(target_os = \"linux\"))"
       (defun has_graphical_display ()
         (declare (values bool))
         true
         )
       )
    )
  )
(defun emit-run-headless ()
  `(defun run_headless (&target_dir &root_name)
     (declare (type Path &target_dir) (type str &root_name)
              (values i32)
              )
     (let ((root_node (FileNode--new (dot root_name (to_string)) true 0))
           ((tuple scan_tx scan_rx) ((scope channel (angle ScanEvent))))
           (abort (Arc--new (AtomicBool--new false)))
           (target (dot target_dir (to_path_buf)))
           )
       (declare (mutable root_node))
       ,(lprint :msg "scan-start"
                :vars '((dot target (display))))
       ;; HATCH: `move' closure via string (parse-lambda documents this).
       (let ((worker (thread--spawn
                       "move || { scan_directory_recursive(&target, &scan_tx, &abort); }"
                       )
                     )
             )
         (while-let ((Ok (ScanEvent--Batch batch)) (dot scan_rx (recv)))
                    (stmt (merge_scan_batch (ref-mut root_node) target_dir batch None))
                    )
         (let ((_ (dot worker (join)))))
         (let (((tuple file_count total_bytes) (sum_tree_stats (ref-mut root_node))))
           (dot (dot root_node children)
                (sort_unstable_by_key (lambda (a)
                                        (std--cmp--Reverse (dot a size_bytes))
                                        )
                                      )
                )
           ,(lprint :msg "scan-done"
                    :vars '(file_count total_bytes))
           (print_line (format! (string "{}: {} in {} files")
                                root_name
                                (format_bytes total_bytes)
                                file_count
                                )
                       )
           (for (child (ref (dot root_node children)))
                (let ((suffix (if (dot child is_dir)
                                  (string "/")
                                  (string "")
                                  )
                              )
                      )
                  (print_line (format! (string "{}	{}{}")
                                       (format_bytes (dot child size_bytes))
                                       (dot child name)
                                       suffix
                                       )
                              )
                  )
                )
           0
           )
         )
       )
     )
  )
(defun emit-headless ()
  (append
    (list (emit-target-from-args)
          (emit-resolve-target)
          (emit-run-headless)
          )
    (emit-has-display)
    )
  )
