;; layout.lisp --- emitters for the sequential squarified treemap layout.
;; CL-near reformulation (plan decision 4): `for (i, &idx) in enumerate`
;; becomes range + aref; behavior-identical, no destructure support needed.
(in-package :cl-rust-generator)
(defun emit-worst-aspect-ratio ()
  `(defun worst_aspect_ratio (row extra areas row_sum side)
     (declare (type "&[usize]" row) (type "Option<usize>" extra)
              (type "&[f64]" areas) (type f64 row_sum) (type f32 side)
              (values f64)
              )
     (when (or (<= row_sum 0.0) (<= side 0.0))
       (return (scope f64 INFINITY))
       )
     (let (((tuple s2 sum2) (tuple (coerce (* side side) f64) (* row_sum row_sum))))
       (dot (dot row (iter) (copied) (chain extra))
            (map (lambda (idx)
                   (declare (type usize idx) (values f64))
                   (let ((a (aref areas idx)))
                     (if (<= a 0.0)
                         0.0
                         (dot (* s2 (/ a sum2)) (max (/ sum2 (* s2 a))))
                         )
                     )
                   )
                 )
            (fold 0.0 (scope f64 max))
            )
       )
     )
  )
(defun emit-layout-row-wide ()
  `(let ((row_thickness (if is_last
                            (dot rect w)
                            (coerce (/ row_sum (coerce (dot rect h) f64)) f32)
                            )
                         )
         )
           (declare (mutable row_thickness))
           (= row_thickness (dot row_thickness (clamp 0.0 (dot rect w))))
           (let ((current_y (dot rect y)))
             (declare (mutable current_y))
             (for (k (range 0 (dot row (len))))
                  (let ((idx (aref row k))
                        (item_h (dot (if (== k (- (dot row (len)) 1))
                                         (- (+ (dot rect y) (dot rect h)) current_y)
                                         (coerce (* (/ (aref areas (aref row k)) row_sum)
                                                    (coerce (dot rect h) f64)
                                                    )
                                                 f32
                                                 )
                                         )
                                     (max 0.0)
                                     )
                                )
                        )
                    (= (dot (aref children idx) target_rect)
                       (Rect--new (dot rect x) current_y row_thickness item_h)
                       )
                    (incf current_y item_h)
                    )
                  )
             )
           (incf (dot rect x) row_thickness)
           (= (dot rect w) (dot (- (dot rect w) row_thickness) (max 0.0)))
           )
  )
(defun emit-layout-row-tall ()
  `(let ((row_thickness (if is_last
                            (dot rect h)
                            (coerce (/ row_sum (coerce (dot rect w) f64)) f32)
                            )
                         )
         )
           (declare (mutable row_thickness))
           (= row_thickness (dot row_thickness (clamp 0.0 (dot rect h))))
           (let ((current_x (dot rect x)))
             (declare (mutable current_x))
             (for (k (range 0 (dot row (len))))
                  (let ((idx (aref row k))
                        (item_w (dot (if (== k (- (dot row (len)) 1))
                                         (- (+ (dot rect x) (dot rect w)) current_x)
                                         (coerce (* (/ (aref areas (aref row k)) row_sum)
                                                    (coerce (dot rect w) f64)
                                                    )
                                                 f32
                                                 )
                                         )
                                     (max 0.0)
                                     )
                                )
                        )
                    (= (dot (aref children idx) target_rect)
                       (Rect--new current_x (dot rect y) item_w row_thickness)
                       )
                    (incf current_x item_w)
                    )
                  )
             )
           (incf (dot rect y) row_thickness)
           (= (dot rect h) (dot (- (dot rect h) row_thickness) (max 0.0)))
           )
  )
(defun emit-layout-row ()
  `(defun layout_row (&children row areas row_sum &rect is_last)
     (declare (type "[FileNode]" &children) (type "&[usize]" row)
              (type "&[f64]" areas) (type f64 row_sum) (type Rect &rect)
              (type bool is_last)
              (mutable &children &rect)
              )
     (when (dot row (is_empty))
       (return)
       )
     (when (or (<= (dot rect w) 0.0) (<= (dot rect h) 0.0) (<= row_sum 0.0))
       (for (k (range 0 (dot row (len))))
            (= (dot (aref children (aref row k)) target_rect)
               (Rect--new (dot rect x) (dot rect y) 0.0 0.0)
               )
            )
       (return)
       )
     (if (>= (dot rect w) (dot rect h))
         ,(emit-layout-row-wide)
         ,(emit-layout-row-tall)
         )
     )
  )
(defun emit-squarify-flush ()
  `(progn
                              (layout_row (ref-mut (dot node children))
                                          (ref (dot ws row))
                                          (ref (dot ws areas))
                                          row_sum
                                          (ref-mut remaining_rect)
                                          false
                                          )
                              (dot (dot ws row) (clear))
                              (dot (dot ws row) (push i))
                              (= row_sum (aref (dot ws areas) i))
                              (when (or (<= (dot remaining_rect w) 0.0)
                                        (<= (dot remaining_rect h) 0.0)
                                        )
                                (for (j (range (+ i 1) (dot (dot node children) (len))))
                                     (= (dot (aref (dot node children) j) target_rect)
                                        (Rect--new (dot remaining_rect x)
                                                   (dot remaining_rect y)
                                                   0.0
                                                   0.0
                                                   )
                                        )
                                     )
                                (break)
                                )
                              )
  )
(defun emit-squarify-step ()
  `(if (<= (aref (dot ws areas) i) 0.0)
                    (progn
                      (= (dot (aref (dot node children) i) target_rect)
                         (Rect--new (dot remaining_rect x) (dot remaining_rect y) 0.0 0.0)
                         )
                      (continue)
                      )
                    (progn
                      (let ((side (dot (dot remaining_rect w) (min (dot remaining_rect h))))
                            (worst_with (worst_aspect_ratio (ref (dot ws row))
                                                            (Some i)
                                                            (ref (dot ws areas))
                                                            (+ row_sum (aref (dot ws areas) i))
                                                            side
                                                            )
                                        )
                            (worst_without (worst_aspect_ratio (ref (dot ws row))
                                                               None
                                                               (ref (dot ws areas))
                                                               row_sum
                                                               side
                                                               )
                                           )
                            )
                        (if (or (dot (dot ws row) (is_empty)) (<= worst_with worst_without))
                            (progn
                              (dot (dot ws row) (push i))
                              (incf row_sum (aref (dot ws areas) i))
                              )
                             ,(emit-squarify-flush)
                            )
                        )
                      )
                    )
  )
(defun emit-squarify-children ()
  `(defun squarify_children (&node &ws)
     (declare (type FileNode &node) (type LayoutWorkspace &ws)
              (mutable &node &ws)
              )
     (when (or (dot (dot node children) (is_empty)) (== (dot node size_bytes) 0))
       (return)
       )
     (when (not (dot node is_sorted))
       (dot (dot node children)
            (sort_unstable_by_key (lambda (a)
                                    (std--cmp--Reverse (dot a size_bytes))
                                    )
                                  )
            )
       (= (dot node is_sorted) true)
       )
     (let ((total_bytes (dot (dot node children) (iter) (map (lambda (c) (dot c size_bytes))) (sum))))
       (declare (type u64 total_bytes))
       (when (== total_bytes 0)
         (return)
         )
       (let ((total_area (coerce (* (dot (dot node target_rect) w) (dot (dot node target_rect) h)) f64)))
         (dot (dot ws areas) (clear))
         (dot (dot ws areas)
              (extend (dot (dot node children)
                           (iter)
                           (map (lambda (c)
                                  (* (coerce (dot c size_bytes) f64)
                                     (/ total_area (coerce total_bytes f64))
                                     )
                                  )
                                )
                           )
                      )
              )
         (let ((remaining_rect (dot node target_rect))
               (row_sum 0.0)
               )
           (declare (mutable remaining_rect row_sum))
           (dot (dot ws row) (clear))
           (for (i (range 0 (dot (dot node children) (len))))
                ,(emit-squarify-step)
                )
           (when (not (dot (dot ws row) (is_empty)))
             (layout_row (ref-mut (dot node children))
                         (ref (dot ws row))
                         (ref (dot ws areas))
                         row_sum
                         (ref-mut remaining_rect)
                         true
                         )
             )
           )
         )
       )
     )
  )
(defun emit-collapse-and-sequential ()
  (list
    `(defun collapse_descendants (&node rect)
       (declare (type FileNode &node) (type Rect rect) (mutable &node))
       (for (child (ref-mut (dot node children)))
            (= (dot child target_rect) rect)
            (collapse_descendants child rect)
            )
       )
    `(defun layout_treemap_sequential (&node &ws)
       (declare (type FileNode &node) (type LayoutWorkspace &ws)
                (mutable &node &ws)
                )
       (when (or (dot (dot node children) (is_empty)) (== (dot node size_bytes) 0))
         (return)
         )
       (squarify_children node ws)
       (for (child (ref-mut (dot node children)))
            (when (and (dot child is_dir) (< 0 (dot child size_bytes)))
              (if (and (<= 6.0 (dot (dot child target_rect) w))
                       (<= 6.0 (dot (dot child target_rect) h))
                       )
                  (progn
                    (= (dot child target_rect)
                       (Rect--new (+ (dot (dot child target_rect) x) 1.0)
                                  (+ (dot (dot child target_rect) y) 1.0)
                                  (dot (- (dot (dot child target_rect) w) 2.0) (max 1.0))
                                  (dot (- (dot (dot child target_rect) h) 2.0) (max 1.0))
                                  )
                       )
                    (layout_treemap_sequential child ws)
                    )
                  (collapse_descendants child (dot child target_rect))
                  )
              )
            )
       )
    )
  )
(defun emit-sum-tree-stats ()
  `(defun sum_tree_stats (&node)
     (declare (type FileNode &node) (mutable &node) (values "(u64, u64)"))
     (when (not (dot node is_dir))
       (return (paren 1 (dot node size_bytes)))
       )
     (let ((f 0)
           (b 0)
           )
       (declare (type u64 f b) (mutable f b))
       (for (c (ref-mut (dot node children)))
            (let (((tuple cf cb) (sum_tree_stats c)))
              (incf f cf)
              (incf b cb)
              )
            )
       (when (!= (dot node size_bytes) b)
         (= (dot node size_bytes) b)
         (= (dot node is_sorted) false)
         )
       (paren f b)
       )
     )
  )
(defun emit-layout ()
  (append
    (list (emit-worst-aspect-ratio)
          (emit-layout-row)
          (emit-squarify-children)
          (emit-sum-tree-stats)
          )
    (emit-collapse-and-sequential)
    )
  )
