;; main.lisp --- emitter for the entry point (headless switch + GUI).
(in-package :cl-rust-generator)
(defun emit-main-fn ()
  `(defun main ()
     (let ((args (dot (std--env--args) (collect))))
       (declare (type "Vec<String>" args))
       (let ((explicit_headless
              (dot args
                   (iter)
                   (any (lambda (a)
                          (or (== a (string "--headless"))
                              (== a (string "--scan-only"))
                              )
                          )
                        )
                   )
              )
             )
         (when (or explicit_headless (not (has_graphical_display)))
           (when (not explicit_headless)
             (eprintln! (string "No graphical display detected (neither DISPLAY nor WAYLAND_DISPLAY is set); running in headless scan mode. Pass --headless to silence this note, or run with an X server (e.g. `xvfb-run ./treemap-disk-analyzer <dir>`) for the GUI."))
             )
           (let (((tuple target_dir root_name) (resolve_target (ref args))))
             (std--process--exit (run_headless (ref target_dir) (ref root_name)))
             )
           )
         )
       )
     ;; NOTE: Window::from_config (what #[macroquad::main] expands to) lets
     ;; the headless check run before miniquad ever calls XOpenDisplay().
     (macroquad--Window--from_config (window_conf) (gui_main))
     )
  )
(defun emit-main ()
  (list (emit-main-fn))
  )
