;; render.lisp --- emitters for animation, cushions and hover rendering.
;; find_hovered_path: lifetime via string fn-name (spike-proven).
;; push('/') as push_str("/") — same bytes, no char-literal form needed.
(in-package :cl-rust-generator)
(defun emit-update-animations ()
  `(defun update_animations (&node dt now)
     (declare (type FileNode &node) (type f32 dt) (type Instant now)
              (mutable &node)
              (values bool)
              )
     (let ((still_anim false))
       (declare (mutable still_anim))
       (if (or (< 0.1 (dot (- (dot node target_rect x) (dot node current_rect x)) (abs)))
               (< 0.1 (dot (- (dot node target_rect y) (dot node current_rect y)) (abs)))
               (< 0.1 (dot (- (dot node target_rect w) (dot node current_rect w)) (abs)))
               (< 0.1 (dot (- (dot node target_rect h) (dot node current_rect h)) (abs)))
               )
           (let ((tt (- 1.0 (dot (* -14.0 dt) (exp)))))
             (= (dot (dot node current_rect) x)
                (+ (dot (dot node current_rect) x)
                   (* (- (dot (dot node target_rect) x) (dot (dot node current_rect) x)) tt)
                   )
                )
             (= (dot (dot node current_rect) y)
                (+ (dot (dot node current_rect) y)
                   (* (- (dot (dot node target_rect) y) (dot (dot node current_rect) y)) tt)
                   )
                )
             (= (dot (dot node current_rect) w)
                (+ (dot (dot node current_rect) w)
                   (* (- (dot (dot node target_rect) w) (dot (dot node current_rect) w)) tt)
                   )
                )
             (= (dot (dot node current_rect) h)
                (+ (dot (dot node current_rect) h)
                   (* (- (dot (dot node target_rect) h) (dot (dot node current_rect) h)) tt)
                   )
                )
             (= still_anim true)
             )
           (= (dot node current_rect) (dot node target_rect))
           )
       (when (< 0.0 (dot node growth_pulse))
         (= (dot node growth_pulse) (dot (- (dot node growth_pulse) (* dt 1.5)) (max 0.0)))
         (= still_anim (or still_anim (< 0.001 (dot node growth_pulse))))
         )
       (when (and (< 0.0 (dot node growth_rate))
                  (< 2.0 (dot (- now (dot node last_change_time)) (as_secs_f32)))
                  )
         (= (dot node growth_rate) 0.0)
         (= still_anim true)
         )
       ;; NOTE: call first — `||` short-circuits, so the accumulator
       ;; comes second (same evaluation order as `|=` in the reference).
       (for (child (ref-mut (dot node children)))
            (= still_anim (or (update_animations child dt now) still_anim))
            )
       still_anim
       )
     )
  )
(defun emit-snap-tree ()
  `(defun snap_tree (&node)
     (declare (type FileNode &node) (mutable &node))
     (= (dot node current_rect) (dot node target_rect))
     (for (child (ref-mut (dot node children)))
          (snap_tree child)
          )
     )
  )
(defun emit-cushion-rect ()
  `(defun draw_cushion_rect (rect base_color pulse)
     (declare (type Rect rect) (type Color base_color) (type f32 pulse))
     (let ((fill_color
            (if (< 0.0 pulse)
                (let ((pulse_color (Color--new 0.3s0 1.0s0 0.4s0 1.0s0)))
                  (Color--new
                    (+ (* (dot base_color r) (- 1.0 pulse)) (* (dot pulse_color r) pulse))
                    (+ (* (dot base_color g) (- 1.0 pulse)) (* (dot pulse_color g) pulse))
                    (+ (* (dot base_color b) (- 1.0 pulse)) (* (dot pulse_color b) pulse))
                    1.0s0
                    )
                  )
                base_color
                )
            )
           )
       (draw_rectangle (dot rect x) (dot rect y) (dot rect w) (dot rect h) fill_color)
       (when (and (<= 4.0 (dot rect w)) (<= 4.0 (dot rect h)))
         (let ((bevel (dot (* (dot (dot rect w) (min (dot rect h))) 0.12)
                           (clamp 1.0 5.0)
                           )
                      )
               )
           (draw_rectangle (dot rect x) (dot rect y) (dot rect w) bevel
                           (Color--new 1.0s0 1.0s0 1.0s0 0.22s0)
                           )
           (draw_rectangle (dot rect x) (dot rect y) bevel (dot rect h)
                           (Color--new 1.0s0 1.0s0 1.0s0 0.22s0)
                           )
           (draw_rectangle (dot rect x) (+ (dot rect y) (- (dot rect h) bevel))
                           (dot rect w) bevel
                           (Color--new 0.0s0 0.0s0 0.0s0 0.35s0)
                           )
           (draw_rectangle (+ (dot rect x) (- (dot rect w) bevel)) (dot rect y)
                           bevel (dot rect h)
                           (Color--new 0.0s0 0.0s0 0.0s0 0.35s0)
                           )
           (draw_rectangle_lines (dot rect x) (dot rect y) (dot rect w) (dot rect h)
                                 1.0
                                 (Color--new 0.05s0 0.05s0 0.08s0 0.5s0)
                                 )
           )
         )
       (when (< 0.05 pulse)
         (draw_rectangle_lines (- (dot rect x) 1.0) (- (dot rect y) 1.0)
                               (+ (dot rect w) 2.0) (+ (dot rect h) 2.0)
                               2.0
                               (Color--new 0.4s0 1.0s0 0.5s0 (* pulse 0.8))
                               )
         )
       )
     )
  )
(defun emit-render-label ()
  `(when (and (< 55.0 screen_w) (< 18.0 screen_h))
     (let ((label (if (< 1024.0 (dot node growth_rate))
                      (format! (string "{} [+{}/s]")
                               (dot node name)
                               (format_bytes (coerce (dot node growth_rate) u64))
                               )
                      (dot node name (clone))
                      )
                  )
           )
       (let ((max_chars (coerce (/ (- screen_w 10.0) 7.2) usize))
             (display_label (truncate_label (ref label) max_chars))
             )
         (draw_text (ref display_label) (+ screen_x 5.0) (+ screen_y 14.0) 14.0 BLACK)
         (stmt (draw_text (ref display_label) (+ screen_x 4.0) (+ screen_y 13.0) 14.0 WHITE))
         )
       )
     )
  )
(defun emit-render-treemap ()
  `(defun render_treemap (&node view_min view_max camera_pos camera_zoom)
     (declare (type FileNode &node) (type Vec2 view_min view_max camera_pos)
              (type f32 camera_zoom)
              )
     (let ((r (dot node current_rect)))
       (when (or (< (dot view_max x) (dot r x))
                 (< (+ (dot r x) (dot r w)) (dot view_min x))
                 (< (dot view_max y) (dot r y))
                 (< (+ (dot r y) (dot r h)) (dot view_min y))
                 )
         (return)
         )
       (let ((screen_x (* (+ (dot r x) (dot camera_pos x)) camera_zoom))
             (screen_y (* (+ (dot r y) (dot camera_pos y)) camera_zoom))
             (screen_w (* (dot r w) camera_zoom))
             (screen_h (* (dot r h) camera_zoom))
             )
         (when (or (< screen_w 1.0) (< screen_h 1.0))
           (return)
           )
         (let ((screen_rect (Rect--new screen_x screen_y screen_w screen_h)))
           (if (dot (dot node children) (is_empty))
               (draw_cushion_rect screen_rect (dot node color) (dot node growth_pulse))
               (progn
                 (when (or (< screen_w 4.0) (< screen_h 4.0))
                   (draw_rectangle screen_x screen_y screen_w screen_h
                                   (Color--new 0.16s0 0.18s0 0.23s0 1.0s0)
                                   )
                   (return)
                   )
                 (for (child (ref (dot node children)))
                      (render_treemap child view_min view_max camera_pos camera_zoom)
                      )
                 (draw_rectangle_lines screen_x screen_y screen_w screen_h
                                       1.0
                                       (Color--new 0.0s0 0.0s0 0.0s0 0.5s0)
                                       )
                 )
               )
           ,(emit-render-label)
           )
         )
       )
     )
  )
(defun emit-find-hovered ()
  `(defun "find_hovered_path<'a>" ("node: &'a FileNode" "pt: Vec2" "path_out: &mut String")
     (declare (values "Option<&'a FileNode>"))
     (when (not (dot (dot node current_rect) (contains pt)))
       (return None)
       )
     (when (not (dot path_out (is_empty)))
       (dot path_out (push (char /)))
       )
     (dot path_out (push_str (ref (dot node name))))
     (for (child (ref (dot node children)))
          (when (dot (dot child current_rect) (contains pt))
            (return (find_hovered_path child pt path_out))
            )
          )
     (Some node)
     )
  )
(defun emit-render ()
  (list (emit-update-animations)
        (emit-snap-tree)
        (emit-cushion-rect)
        (emit-render-treemap)
        (emit-find-hovered)
        )
  )
