;; scan.lisp --- emitters for the robust filesystem scanner.
;; Reformulations (behavior-identical, noted for the walkthrough):
;; - is_virtual_or_special_fs: two #[cfg]-gated fns instead of an inner
;;   #[cfg]-block (same truth table on every platform).
;; - drain(..): std::mem::take on owned locals (same empty-Vec result).
;; - merge_scan_batch takes batch by value (callers never reuse it).
(in-package :cl-rust-generator)
(defun emit-is-virtual ()
  (list
    `(attr "cfg(target_os = \"linux\")"
       (defun is_virtual_or_special_fs (&path)
         (declare (type Path &path) (values bool))
         (or (dot path (starts_with (string "/proc")))
             (dot path (starts_with (string "/sys")))
             (dot path (starts_with (string "/dev")))
             (dot path (starts_with (string "/run")))
             )
         )
       )
    `(attr "cfg(not(target_os = \"linux\"))"
       (defun is_virtual_or_special_fs (&path)
         (declare (type Path &path) (values bool))
         false
         )
       )
    )
  )
(defun emit-scan-dir-arm ()
  `(when (not (is_virtual_or_special_fs (ref path)))
                        (dot scanned_children
                             (push (FileNode--new name true 0))
                             )
                        (dot subdirs_to_recurse (push path))
                        )
  )
(defun emit-scan-file-arm ()
  `(when (dot file_type (is_file))
                        ;; 03-parity: report instead of unwrap_or(0).
                        (let ((size (case (dot entry (metadata))
                                      ((Ok m) (dot m (len)))
                                      ((Err e)
                                       (report_skip (string "metadata")
                                                    (ref path)
                                                    e
                                                    )
                                       0
                                       )
                                      )
                                   )
                              )
                          ;; 01_more keeps 0-byte files; only >2^48 skipped.
                          (when (not (< (<< 1 48) size))
                            (dot scanned_children
                                 (push (FileNode--new name false size))
                                 )
                            )
                          )
                        )
  )
(defun emit-scan-finish ()
  (list
    `(let ((_ (dot tx (send (ScanEvent--Batch
                             (make-instance DirectoryBatch
                                            :parent_path (dot dir_path (to_path_buf))
                                            :children scanned_children
                                            )
                             )
                           )
                 )
             )
       )
       )
    `(for (subdir subdirs_to_recurse)
          (scan_directory_recursive (ref subdir) tx abort)
          )
    )
  )
(defun emit-scan-recursive ()
  `(defun scan_directory_recursive (&dir_path &tx &abort)
     (declare (type Path &dir_path)
              (type "Sender<ScanEvent>" &tx)
              (type "Arc<AtomicBool>" &abort)
              )
     (when (or (dot abort (load Ordering--Relaxed))
               (is_virtual_or_special_fs dir_path)
               )
       (return)
       )
     (let ((entries (case (fs--read_dir dir_path)
                      ((Ok iter) iter)
                      ((Err e)
                       (report_skip (string "read_dir") dir_path e)
                       (return)
                       )
                      )
                    )
           )
       (let ((scanned_children (Vec--new))
             (subdirs_to_recurse (Vec--new))
             )
         (declare (mutable scanned_children subdirs_to_recurse))
         (for (entry (dot entries (flatten)))
              (when (dot abort (load Ordering--Relaxed))
                (return)
                )
              (let ((file_type (case (dot entry (file_type))
                                 ((Ok ft) ft)
                                 ((Err e)
                                  (report_skip (string "file_type")
                                               (ref (dot entry (path)))
                                               e
                                               )
                                  (continue)
                                  )
                                 )
                               )
                    )
                (when (dot file_type (is_symlink))
                  (continue)
                  )
                (let ((path (dot entry (path)))
                      (name (dot entry (file_name) (to_string_lossy) (into_owned)))
                      )
                  (if (dot file_type (is_dir))
                      ,(emit-scan-dir-arm)
                      ,(emit-scan-file-arm)
                      )
                  )
                )
              )
         ,@(emit-scan-finish)
         )
       )
     )
  )
;; NOTE: batch by value (01_more: &mut). Callers never reuse it;
;; this avoids a `mut` binding inside the while-let pattern.
(defun emit-merge-batch ()
  `(defun merge_scan_batch (&root_node &target_dir batch watcher_mgr)
     (declare (type FileNode &root_node)
              (type Path &target_dir)
              (type DirectoryBatch batch)
              (type "Option<&mut WatcherManager>" watcher_mgr)
              (mutable &root_node)
              (values bool)
              )
     (if-let ((Some wm) watcher_mgr)
             (dot wm (register_dir (ref (dot batch parent_path))))
             )
     (if-let ((Ok rel) (dot (dot batch parent_path) (strip_prefix target_dir)))
             (let ((components (dot rel (iter) (collect))))
               (declare (type "Vec<&OsStr>" components))
               (if-let ((Some parent) (dot root_node (find_mut (ref components))))
                       (progn
                         (for (child (dot batch children))
                              (merge_scanned_node parent child)
                              )
                         (return true)
                         )
                       )
               )
             )
     false
     )
  )
(defun emit-merge-node ()
  `(defun merge_scanned_node (&parent new_child)
     (declare (type FileNode &parent) (type FileNode new_child)
              (mutable &parent new_child)
              )
     (if-let ((Some existing)
              (dot (dot parent children)
                   (iter_mut)
                   (find (lambda (c)
                           (and (== (dot c name) (dot new_child name))
                                (== (dot c is_dir) (dot new_child is_dir))
                                )
                           )
                         )
                   )
              )
             (if (dot existing is_dir)
                 (for (child (std--mem--take (ref-mut (dot new_child children))))
                      (merge_scanned_node existing child)
                      )
                 (when (!= (dot existing size_bytes) (dot new_child size_bytes))
                   (= (dot existing size_bytes) (dot new_child size_bytes))
                   )
                 )
             (progn
               (= (dot new_child target_rect) (dot parent target_rect))
               (= (dot new_child current_rect) (dot parent current_rect))
               (dot (dot parent children) (push new_child))
               (= (dot parent is_sorted) false)
               )
             )
     )
  )
(defun emit-scan ()
  (append
    (emit-is-virtual)
    (list (emit-scan-recursive)
          (emit-merge-batch)
          (emit-merge-node)
          )
    )
  )
