;; tests.lisp --- emitters for generated unit tests (mod tests port).
(in-package :cl-rust-generator)
;; owned: (string s) is &str; FileNode::new etc. need String.
(defun owned (s)
  `(dot (string ,s) (to_string))
  )
(defun emit-truncate-tests ()
  (list
    "#[test]"
    `(defun truncate_ascii_label ()
       (assert_eq! (truncate_label (string "hello world") 8) (string "hello .."))
       (assert_eq! (truncate_label (string "hi") 8) (string "hi"))
       (assert_eq! (truncate_label (string "12345678") 8) (string "12345678"))
       )
    "#[test]"
    `(defun truncate_cjk_label_never_panics ()
       (assert_eq! (truncate_label (string "abc还def") 6) (string "abc还.."))
       (assert_eq! (truncate_label (string "abc还def") 7) (string "abc还def"))
       (assert_eq! (truncate_label (string "还还还还还") 4) (string "还还.."))
       )
    "#[test]"
    `(defun truncate_emoji_and_narrow_width ()
       (assert_eq! (truncate_label (string "a🦀b") 3) (string "a🦀b"))
       (assert_eq! (truncate_label (string "a🦀bcd") 4) (string "a🦀.."))
       (assert_eq! (truncate_label (string "anything") 3) (string "anything"))
       (assert_eq! (truncate_label (string "anything") 2) (string "anything"))
       )
    )
  )
(defun emit-target-arg-test ()
  (list
    "#[test]"
    `(defun target_arg_parsing_skips_flags ()
       (let ((args (vec! ,(owned "treemap-more-lisp") ,(owned "--headless") ,(owned "/tmp"))))
         (assert_eq! (target_from_args (ref args)) (PathBuf--from (string "/tmp")))
         )
       (let ((bare (vec! ,(owned "treemap-more-lisp"))))
         (assert_eq! (target_from_args (ref bare)) (PathBuf--from (string ".")))
         )
       )
    )
  )
(defun emit-merge-batch-test ()
  (list
    "#[test]"
    `(defun merge_scan_batch_reports_whether_tree_changed ()
       (let ((target (PathBuf--from (string "/tmp/treemap-merge-probe")))
             (root (FileNode--new ,(owned "root") true 0))
             )
         (declare (mutable root))
         (let ((batch (make-instance DirectoryBatch
                                     :parent_path (dot target (clone))
                                     :children (vec! (FileNode--new ,(owned "a.txt") false 10))
                                     )
                     )
               )
           (assert! (merge_scan_batch (ref-mut root) (ref target) batch None))
           (assert_eq! (dot (dot root children) (len)) 1)
           )
         (let ((orphan (make-instance DirectoryBatch
                                      :parent_path (dot target (join (string "nope")))
                                      :children (vec! (FileNode--new ,(owned "b.txt") false 5))
                                      )
                       )
               )
           (assert! (not (merge_scan_batch (ref-mut root) (ref target) orphan None)))
           (assert_eq! (dot (dot root children) (len)) 1)
           )
         )
       )
    )
  )
(defun emit-layout-test-tree ()
  (list
    `(attr "cfg(test)"
       (defun layout_test_tree ()
         (declare (values FileNode))
       (let ((root (FileNode--new ,(owned "root") true 0)))
         (declare (mutable root))
         (= (dot root target_rect) (Rect--new 0.0 0.0 1000.0 1000.0))
         (let ((big (FileNode--new ,(owned "big") true 0)))
           (declare (mutable big))
           (= (dot big children)
              (vec! (FileNode--new ,(owned "b1") false 400)
                    (FileNode--new ,(owned "b2") false 200)
                    )
              )
           (= (dot root children)
              (vec! big
                    (FileNode--new ,(owned "mid") false 300)
                    (FileNode--new ,(owned "small") false 100)
                    )
              )
           )
         (sum_tree_stats (ref-mut root))
         root
         )
       )
       )
    )
  )
(defun emit-layout-area-check ()
  `(let ((parent_area (* (dot (dot root target_rect) w)
                               (dot (dot root target_rect) h)
                               )
                            )
               (children_area (dot (dot root children)
                                   (iter)
                                   (map (lambda (c)
                                          (* (dot (dot c target_rect) w)
                                             (dot (dot c target_rect) h)
                                             )
                                          )
                                        )
                                   (sum)
                                   )
                              )
               )
           (declare (type f32 children_area))
           (assert! (< (/ (dot (- children_area parent_area) (abs)) parent_area) 0.005))
           )
  )
(defun emit-layout-overlap-test ()
  (list
    "#[test]"
    `(defun layout_conserves_area_sorts_and_avoids_overlap ()
       (let ((root (layout_test_tree))
             (ws (make-instance LayoutWorkspace
                                :areas (Vec--new)
                                :row (Vec--new)
                                )
                 )
             )
         (declare (mutable root ws))
         (layout_treemap_sequential (ref-mut root) (ref-mut ws))
         (let ((sizes (dot (dot root children)
                           (iter)
                           (map (lambda (c) (dot c size_bytes)))
                           (collect)
                           )
                       )
               )
           (declare (type "Vec<u64>" sizes))
           (assert_eq! sizes (vec! 600 300 100))
           )
         ,(emit-layout-area-check)
         (for (ai (range 0 (dot (dot root children) (len))))
              (for (bi (range (+ ai 1) (dot (dot root children) (len))))
                   (let ((ra (dot (aref (dot root children) ai) target_rect))
                         (rb (dot (aref (dot root children) bi) target_rect))
                         )
                     (assert! (not (and (< (dot ra x) (+ (dot rb x) (dot rb w)))
                                            (< (dot rb x) (+ (dot ra x) (dot ra w)))
                                            (< (dot ra y) (+ (dot rb y) (dot rb h)))
                                            (< (dot rb y) (+ (dot ra y) (dot ra h)))
                                            )
                                       )
                              )
                     )
                   )
              )
         )
       )
    )
  )
(defun emit-layout-test ()
  (append
    (emit-layout-test-tree)
    (emit-layout-overlap-test)
    )
  )
(defun emit-tests ()
  (append
    (emit-truncate-tests)
    (emit-target-arg-test)
    (emit-merge-batch-test)
    (emit-layout-test)
    )
  )
