;; watcher.lisp --- emitter for the platform-adaptive live watcher.
;; Reformulation: is_native_recursive via two cfg-gated helpers
;; (attr on a let would scope the binding). Same truth table.
(in-package :cl-rust-generator)
(defun emit-watcher-struct ()
  `(defstruct0 WatcherManager
     (watcher "Option<RecommendedWatcher>")
     (rx "Receiver<notify::Result<Event>>")
     (watched_dirs "HashSet<PathBuf>")
     (is_native_recursive bool)
     (limit_hit bool)
     (error_msg "Option<String>")
     )
  )
(defun emit-native-recursive ()
  (list
    `(attr "cfg(any(target_os = \"macos\", target_os = \"windows\"))"
       (defun native_recursive ()
         (declare (values bool))
         true
         )
       )
    `(attr "cfg(not(any(target_os = \"macos\", target_os = \"windows\")))"
       (defun native_recursive ()
         (declare (values bool))
         false
         )
       )
    )
  )
(defun emit-watcher-opt-case ()
  `(case (notify--recommended_watcher
           (space move (lambda (res)
                         (let ((_ (dot tx (send res))))
                           )
                         )
               )
           )
     ((Ok w) (Some w))
     ((Err e)
      (eprintln! (string "[Watcher] Initialization failed: {e}"))
      (return (make-instance Self
                             :watcher None
                             rx
                             :watched_dirs (HashSet--new)
                             is_native_recursive
                             :limit_hit false
                             :error_msg (Some (format! (string "Init error: {e}")))
                             )
                )
      )
     )
  )
(defun emit-watcher-watch-root ()
  `(if-let ((Some watcher) (dot watcher_opt (as_mut)))
           (let ((mode (if is_native_recursive
                           RecursiveMode--Recursive
                           RecursiveMode--NonRecursive
                           )
                       )
                 )
             (case (dot watcher (watch root_path mode))
               ((Ok _)
                (let ((_ (dot watched_dirs
                               (insert (dot root_path (to_path_buf)))
                               )
                          )
                      )
                  )
                )
               ((Err e)
                (eprintln! (string "[Watcher] Failed to watch root '{}': {e}")
                           (dot root_path (display))
                           )
                (let ((err_str (dot e (to_string)))
                      )
                  (if (or (dot err_str (contains (string "os error 28")))
                          (dot err_str (contains (string "No space left")))
                          )
                      (= limit_hit true)
                      (= error_msg (Some err_str))
                      )
                  )
                )
               )
             )
           )
  )
(defun emit-watcher-new ()
  `(defun new (&root_path)
     (declare (type Path &root_path) (values Self))
     (let (((tuple tx rx) ((scope channel (angle "notify::Result<Event>"))))
           (is_native_recursive (native_recursive))
           (watcher_opt
            ,(emit-watcher-opt-case)
            )
           )
       (declare (mutable watcher_opt))
       (let ((watched_dirs (HashSet--new))
             (error_msg None)
             (limit_hit false)
             )
         (declare (mutable watched_dirs error_msg limit_hit))
         ,(emit-watcher-watch-root)
         (make-instance Self
                        :watcher watcher_opt
                        rx
                        watched_dirs
                        is_native_recursive
                        limit_hit
                        error_msg
                        )
         )
       )
     )
  )
(defun emit-register-dir ()
  `(defun register_dir ("&mut self" "&path")
     (declare (type Path &path))
     (when (or (dot self is_native_recursive)
               (dot self limit_hit)
               (is_virtual_or_special_fs path)
               )
       (return)
       )
     (when (dot (dot self watched_dirs) (contains path))
       (return)
       )
     (if-let ((Some watcher) (dot (dot self watcher) (as_mut)))
             (case (dot watcher (watch path RecursiveMode--NonRecursive))
               ((Ok _)
                (let ((_ (dot (dot self watched_dirs)
                               (insert (dot path (to_path_buf)))
                               )
                          )
                      )
                  )
                )
               ((Err e)
                (let ((err_str (dot e (to_string)))
                      )
                  (if (or (dot err_str (contains (string "os error 28")))
                          (dot err_str (contains (string "No space left")))
                          )
                      (progn
                        (when (not (dot self limit_hit))
                          ;; Split \n out: eprintln!() equals the blank line.
                          (eprintln!)
                          (eprintln! (string "[Watcher Warning] Linux inotify user watch limit reached!"))
                          (eprintln! (string "Run: sudo sysctl fs.inotify.max_user_watches=524288"))
                          (eprintln!)
                          (= (dot self limit_hit) true)
                          )
                        )
                      (= (dot self error_msg) (Some err_str))
                      )
                  )
                )
               )
             )
     )
  )
(defun emit-watcher ()
  (append
    (list (emit-watcher-struct)
          `(impl WatcherManager
                 ,(emit-watcher-new)
                 ,(emit-register-dir)
                 )
          )
    (emit-native-recursive)
    )
  )
