;; layout.lisp --- emitters for the squarified treemap layout.
(in-package :cl-rust-generator)
(defun emit-worst ()
  `(defun worst (areas row sum side)
     (declare (type "&[f64]" areas) (type "&[usize]" row)
              (type f64 sum) (type f32 side) (values f64))
     (let (((tuple s2 sum2) (tuple (coerce (* side side) f64) (* sum sum))))
       (dot row (iter)
                  (map (lambda (i)
                         (declare (type "&usize" i))
                         (dot (/ (* s2 (aref areas (deref i))) sum2)
                              (max (/ sum2 (* s2 (aref areas (deref i))))))))
                  (fold 0.0 (scope f64 max)))))
  )
(defun emit-layout-row ()
  `(defun layout_row (nodes areas row sum r)
     (declare (type "&mut [Node]" nodes) (type "&[f64]" areas)
              (type "&[usize]" row) (type f64 sum) (type "&mut Rect" r))
     (let ((side (dot (dot r w) (min (dot r h))))
           (thickness (coerce (/ sum (coerce side f64)) f32))
           (is_horiz (< (dot r w) (dot r h))))
       (let ((offset (if is_horiz (dot r x) (dot r y))))
         (declare (mutable offset))
         (for (i row)
           (let ((item_len (coerce (* (/ (aref areas (deref i)) sum) (coerce side f64)) f32)))
             (= (dot (aref nodes (deref i)) rect)
                (if is_horiz
                    (Rect--new offset (dot r y) item_len thickness)
                    (Rect--new (dot r x) offset thickness item_len)))
             (incf offset item_len)))
         (if is_horiz
             (progn (incf (dot r y) thickness) (decf (dot r h) thickness))
             (progn (incf (dot r x) thickness) (decf (dot r w) thickness))))))
  )
(defun emit-squarify ()
  `(defun squarify (&nodes rect)
     (declare (type "[Node]" &nodes) (type Rect rect) (mutable &nodes rect))
     (let ((total (dot nodes (iter) (map (lambda (n) (dot n size))) (sum))))
       (declare (type u64 total))
       (when (or (== total 0) (<= (dot rect w) 0.0) (<= (dot rect h) 0.0))
         (return))
       (dot nodes (sort_unstable_by_key
                   (lambda (n) (std--cmp--Reverse (dot n size)))))
       (let ((area_mult (/ (coerce (* (dot rect w) (dot rect h)) f64)
                           (coerce total f64))))
         (let ((areas (dot nodes (iter)
                                 (map (lambda (n)
                                        (* (coerce (dot n size) f64) area_mult)))
                                 (collect))))
           (declare (type "Vec<f64>" areas))
           (let ((row (Vec--new)) (row_sum 0.0))
             (declare (mutable row row_sum))
             (for (i (range 0 (dot areas (len))))
               (let ((side (dot rect w (min (dot rect h))))
                     (area (aref areas i))
                     (next_row (dot row (clone))))
                 (declare (mutable next_row))
                 (dot next_row (push i))
                 (if (or (dot row (is_empty))
                         (<= (worst (ref areas) (ref next_row) (+ row_sum area) side)
                             (worst (ref areas) (ref row) row_sum side)))
                     (progn (dot row (push i)) (incf row_sum area))
                     (progn
                       (layout_row nodes (ref areas) (ref row) row_sum (ref-mut rect))
                       (setf row (vec! i)) (setf row_sum area)))))
             (when (not (dot row (is_empty)))
               (layout_row nodes (ref areas) (ref row) row_sum (ref-mut rect)))
             (for (node (dot nodes (iter_mut)))
               (when (and (dot node is_dir)
                          (< 4.0 (dot (dot node rect) w))
                          (< 4.0 (dot (dot node rect) h)))
                 (squarify (ref-mut (dot node children)) (dot node rect)))))))))
  )
