;; render.lisp --- emitters for colors, utils and rendering.
(in-package :cl-rust-generator)
(defun emit-hash-color ()
  `(defun hash_color (&path)
     (declare (type Path &path) (values Color))
     (let ((name (dot path (file_name)
                        (and_then (scope OsStr to_str))
                        (unwrap_or (string ""))))
           (h (dot name (bytes)
                     (fold 0 (lambda (acc b)
                               (declare (type u32 acc) (type u8 b) (values u32))
                               (dot acc (wrapping_add (coerce b u32))))))))
       (Color--from_rgba (coerce (+ (% (* h 37) 160) 80) u8)
                         (coerce (+ (% (* h 59) 160) 80) u8)
                         (coerce (+ (% (* h 83) 160) 80) u8)
                         255)))
  )
(defun emit-color-for-path ()
  `(defun color_for_path (&path)
     (declare (type Path &path) (values Color))
     (let ((ext (dot path (extension)
                       (and_then (scope OsStr to_str))
                       (unwrap_or (string "")))))
       (if ,(ext-is 'ext '("rs" "c" "cpp" "py" "js" "ts" "txt" "md"))
           (Color--new 0.2s0 0.75s0 0.45s0 1.0s0)
           (if ,(ext-is 'ext '("png" "jpg" "jpeg" "svg" "webp"))
               (Color--new 0.2s0 0.65s0 0.95s0 1.0s0)
               (if ,(ext-is 'ext '("mp4" "mkv" "mov" "mp3" "flac"))
                   (Color--new 0.75s0 0.35s0 0.85s0 1.0s0)
                   (if ,(ext-is 'ext '("zip" "tar" "gz" "7z"))
                       (Color--new 0.9s0 0.3s0 0.25s0 1.0s0)
                       (hash_color path)))))))
  )
(defun emit-format-bytes ()
  `(defun format_bytes (b)
     (declare (type u64 b) (values String))
     (let ((units (bracket (string "B") (string "KB") (string "MB")
                           (string "GB") (string "TB")))
           (d (coerce b f64))
           (i 0))
       (declare (type usize i) (mutable d i))
       (while (and (<= 1024.0 d) (< i 4))
         ;; HATCH: (/= d 1024.0) emits d/=(1024.0); rustfmt keeps the
         ;; redundant parens (unused_parens). Proposed upstream in walkthrough.
         "d /= 1024.0;"
         (incf i))
       (format! (string "{:.1} {}") d (aref units i))))
  )
(defun emit-format-bytes-test ()
  (list
    "#[test]"
    `(defun test_format_bytes ()
       ,@(loop for (bytes want) in '((0 "0.0 B") (100 "100.0 B")
                                     (2048 "2.0 KB") (5242880 "5.0 MB"))
               collect `(assert_eq! (format_bytes ,bytes) (string ,want))))
    )
  )
(defun emit-render-tree ()
  `(defun render_tree (node mouse hovered)
     (declare (type &Node node) (type Vec2 mouse)
              (type "&mut Option<String>" hovered))
     (when (or (< (dot node rect w) 1.0) (< (dot node rect h) 1.0))
       (return))
     (if (dot node children (is_empty))
         (progn
           (draw_rectangle (dot node rect x) (dot node rect y)
                           (dot node rect w) (dot node rect h) (dot node color))
           (draw_rectangle_lines (dot node rect x) (dot node rect y)
                                 (dot node rect w) (dot node rect h) 1.0
                                 (Color--new 0.0s0 0.0s0 0.0s0 0.35s0)))
         (progn
           (for (child (ref (dot node children)))
             (render_tree child mouse hovered))
           (draw_rectangle_lines (dot node rect x) (dot node rect y)
                                 (dot node rect w) (dot node rect h) 1.0
                                 (Color--new 0.0s0 0.0s0 0.0s0 0.6s0))))
     (when (and (dot hovered (is_none))
                (dot (dot node rect) (contains mouse)))
       (= (deref hovered)
          (Some (format! (string "{} ({})")
                         (dot node path (display))
                         (format_bytes (dot node size)))))))
  )
