;; scan.lisp --- emitters for filesystem traversal.
(in-package :cl-rust-generator)
(defun emit-scan-tree ()
  `(defun scan_tree (&path)
     (declare (type Path &path) (values Node))
     (let ((node (make-instance Node
                     :path (dot path (to_path_buf)) :size 0 :is_dir true
                     :children (Vec--new) :rect (Rect--default)
                     :color (Color--new 0.15s0 0.17s0 0.22s0 1.0s0))
                 )
           (s (dot path (to_string_lossy)))
           )
       (declare (mutable node))
       (when (or (dot s (starts_with (string "/proc")))
                 (dot s (starts_with (string "/sys")))
                 (dot s (starts_with (string "/dev"))))
         (return node))
       (case (fs--read_dir path)
         ((Ok entries)
          (for (entry_res entries)
            (case entry_res
              ((Ok entry) (scan_entry (ref-mut node) entry))
              ((Err e) (report_skip (string "entry") path e)))))
         ((Err e) (report_skip (string "read_dir") path e)))
       node)
     )
  )
(defun emit-scan-entry ()
  `(defun scan_entry (&node entry)
     (declare (type Node &node) (type "std::fs::DirEntry" entry) (mutable &node))
     (let ((ft (case (dot entry (file_type))
                 ((Ok ft) ft)
                 ((Err e)
                  (progn
                    (report_skip (string "file_type") (ref (dot entry (path))) e)
                    (return))))))
       (when (dot ft (is_symlink)) (return))
       (let ((entry_path (dot entry (path))))
         (if (dot ft (is_dir))
             (let ((child (scan_tree (ref entry_path))))
               (when (< 0 (dot child size))
                 (incf (dot node size) (dot child size))
                 (dot node children (push child))))
             (when (dot ft (is_file))
               (let ((size (case (dot entry (metadata))
                             ((Ok m) (dot m (len)))
                             ((Err e)
                              (progn
                                (report_skip (string "metadata") (ref entry_path) e)
                                0)))))
                 (when (and (< 0 size) (< size (<< 1 48)))
                   (dot node children
                        (push (make-instance Node
                                :color (color_for_path (ref entry_path))
                                :path entry_path size :is_dir false
                                :children (Vec--new) :rect (Rect--default))))))))))))
